#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Copyright: (c) 2021, [Jean Claveau (https://gist.github.com/jclaveau/af2271b9fdf05f7f1983f492af5592f8)]
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import (absolute_import, division, print_function)
__metaclass__ = type
import subprocess
import os
import sys

TEMPLATE = """
# This file is auto generated by a Github hook from the content of the Vagrantfile file of the same folder.
# Caution: All the changes you directly do here will be lost
# Please enable hooks for proper development by running `git config core.hooksPath .githooks`

VAGRANTFILE_CONTENT = \"\"\"
%s
\"\"\"
"""

vagrantfile_path = 'plugins/module_utils/Vagrantfile'

current_dir = os.path.dirname(os.path.realpath(__file__))
os.chdir(current_dir + '/../')

added = subprocess.check_output(["git", "diff", '--cached', '--name-only']) \
    .decode('utf-8') \
    .strip() \
    .split("\n")

if vagrantfile_path not in added:
    # print('No Vagrantfile modification')
    sys.exit()

with open(vagrantfile_path, 'r') as vf:
    vagrantfile_content = vf.read()

    python_content = TEMPLATE % vagrantfile_content

    with open(vagrantfile_path + '.py', 'w') as vf_python:
        vf_python.write(python_content)

subprocess.check_output(["git", "add", vagrantfile_path])
subprocess.check_output(["git", "add", vagrantfile_path + '.py'])
