#!/bin/sh

# https://www.viget.com/articles/two-ways-to-share-git-hooks-with-your-team/
# git config core.hooksPath .githooks

# run from the root of the repo
# .githooks/replace_by_git_vars.py readme.md README.md -v
.githooks/replace_by_git_vars.py readme.md README.md
