name: Ubuntu / Docker
on: [ push ]
jobs:
  provider-integration-tests-docker-on-ubuntu:
    runs-on: ubuntu-latest
    env:
      PY_COLORS: '1'
      ANSIBLE_FORCE_COLOR: '1'
    defaults:
      run:
        working-directory: ansible_collections/jclaveau/vagrant

    steps:
      - name: Clone the repo
        uses: actions/checkout@v2
        with:
          path: ansible_collections/jclaveau/vagrant

      - name: Pass environment variables to the tests
        run: ./tests/integration/integration_config.sh

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Apt update
        run: sudo apt-get update

      - name: Tools for docker installation
        run: sudo apt-get install apt-transport-https ca-certificates curl gnupg lsb-release

      - name: Docker gpg key
        run: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

      - name: Add Dockers repo
        run: echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

      - name: Apt update
        run: sudo apt-get update

      - name: Install Docker
        run:  sudo apt-get install docker-ce docker-ce-cli containerd.io

      - name: Install Vagrant
        run: sudo apt-get install vagrant

      - name: Install vagrant-mutate
        run: vagrant plugin install vagrant-mutate

      - name: Install Vagrant
        run: vagrant plugin list

      - name: Install wheel
        run: pip install wheel

      - name: Install dependencies
        run: pip install -r ./requirements.txt

      - name: Install coverage dependency
        run: pip install --user coverage==4.5.4

      # - name: Cache Vagrant boxes
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/.vagrant.d/boxes
      #     key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
      #     restore-keys: |
      #       ${{ runner.os }}-vagrant-

      - name: Run the integration tests
        run: ansible-test integration --no-temp-workdir --python 3.8 config --tags docker --coverage --color

      - name: Prepare coverage for Codecov.io
        run: ansible-test coverage xml --color

      - uses: codecov/codecov-action@v1 # https://github.com/marketplace/actions/codecov
        with:
          # token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          directory: /home/runner/work/ansible-vagrant-modules/ansible-vagrant-modules/ansible_collections/jclaveau/vagrant/tests/output/reports/
          flags: integrationtests, docker
          name: integration-tests-ubuntu-docker
          fail_ci_if_error: true
          # verbose: true
